"""empty message

Revision ID: 24a1a4d5ca61
Revises: cd6f9adb7799
Create Date: 2021-03-10 17:22:53.331461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a1a4d5ca61'
down_revision = 'cd6f9adb7799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication', schema=None) as batch_op:
        batch_op.alter_column('join_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication', schema=None) as batch_op:
        batch_op.alter_column('join_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
