"""empty message

Revision ID: 476960e873cd
Revises: 37fa7944d38a
Create Date: 2021-02-26 15:59:20.644951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476960e873cd'
down_revision = '37fa7944d38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=35), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentication', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
