"""empty message

Revision ID: ae2f881c1c19
Revises: e0628404ca23
Create Date: 2021-02-25 22:26:29.555626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2f881c1c19'
down_revision = 'e0628404ca23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joiningdetails', schema=None) as batch_op:
        batch_op.drop_column('leave_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joiningdetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('leave_date', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
