"""empty message

Revision ID: b0f00269e496
Revises: cfdbb9fe87b1
Create Date: 2021-02-24 16:03:47.273988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f00269e496'
down_revision = 'cfdbb9fe87b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_Description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('leave_Description')

    # ### end Alembic commands ###
