"""empty message

Revision ID: b507332f87b9
Revises: 0fb45beb28fa
Create Date: 2021-02-24 14:04:00.819513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b507332f87b9'
down_revision = '0fb45beb28fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('basic', sa.Float(precision=2), nullable=False))
    op.alter_column('grade', 'end_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grade', 'end_date',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('grade', 'basic')
    # ### end Alembic commands ###
