"""empty message

Revision ID: cd6f9adb7799
Revises: 1304fd78880f
Create Date: 2021-03-10 17:21:32.196148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6f9adb7799'
down_revision = '1304fd78880f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isAuthenticate', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('designation_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=12), nullable=False),
    sa.Column('basic', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('generateddate', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('fulladdress', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annualleave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('pl', sa.Integer(), nullable=True),
    sa.Column('sl', sa.Integer(), nullable=True),
    sa.Column('cl', sa.Integer(), nullable=True),
    sa.Column('lwp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('starttime', sa.String(length=10), nullable=False),
    sa.Column('endtime', sa.String(length=10), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emp_sal_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('account_no', sa.String(length=25), nullable=False),
    sa.Column('ifsc_code', sa.String(length=10), nullable=False),
    sa.Column('bankname', sa.String(length=30), nullable=False),
    sa.Column('pfaccount_no', sa.String(length=30), nullable=False),
    sa.Column('esi_no', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=25), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('basic', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joiningdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('deactivate_by', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('senction_by_id', sa.Integer(), nullable=True),
    sa.Column('leave_type', sa.String(length=5), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('apply_date', sa.DateTime(), nullable=True),
    sa.Column('senction_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('leave_Description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaldetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=45), nullable=False),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('gender', sa.String(length=7), nullable=False),
    sa.Column('dob', sa.String(length=15), nullable=False),
    sa.Column('bloodgroup', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=26), nullable=False),
    sa.Column('contactno', sa.String(length=16), nullable=False),
    sa.Column('pancardno', sa.String(length=16), nullable=False),
    sa.Column('aadharcardno', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('qualification', sa.String(length=16), nullable=False),
    sa.Column('pass_year', sa.Integer(), nullable=False),
    sa.Column('work_experience', sa.Float(precision=1), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=False),
    sa.Column('projectname', sa.String(length=50), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['authentication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('qualification')
    op.drop_table('personaldetails')
    op.drop_table('leave')
    op.drop_table('joiningdetails')
    op.drop_table('grade')
    op.drop_table('emp_sal_info')
    op.drop_table('attendance_model')
    op.drop_table('annualleave')
    op.drop_table('address')
    op.drop_table('salary')
    op.drop_table('designation_model')
    op.drop_table('authentication')
    # ### end Alembic commands ###
